from datetime import datetime
from pathlib import Path
from cruxpy.repo import port as cruxport
import re
import shutil


class page:
    """
    Class to handle website for portspage.
    It takes a path with ports, obtain their information.
    Then uses them with header and footer to prepare a page.

    """

    def __init__(self, path=".", header="", style="original"):
        self.ports_dir = Path(path, recursive=True)
        self.ports = sorted(list(self.ports_dir.glob("*/Pkgfile")))
        self.content = self.__generate_page(header, style)


    def __make_table(self, key="RWQXc2agtIcYBWpHqhhttRH+067uIV9sEkGPB2FT2uZRmFC712MDQF4Q"):
        table = [
                '<table width="100%" cellspacing="0">',
                '<tr class="header"><td colspan="4">',
                '<strong>Signify public key: </strong>%s</td></tr>'%key,
                ]
        for index, port in enumerate(self.ports):
            current = "even" if index % 2 == 0 else "odd"
            p = cruxport(port)
            line = f'<tr class="{current}"><td><a href="{p.url}">{p.name}</a></td><td><a href="./{p.name}">{p.version}</a></td><td>{p.description}</td><td>{p.update}</td></tr>'
            table.append(line)
        table.append("</table>")
        return table

    def __make_header(self, file, style):
        with open(file) as f:
            content = f.read()
            header = content.splitlines()
        pattern=r'{{ style_name }}'
        new_header = []
        for line in header:
            new_header.append(re.sub(pattern, style, line))
        return new_header

    def __make_footer(self):
        footer = [
            f'<p class="footer">In total {len(self.ports)} ports',
            f'<p class="creator">Generated by portspage.py on {datetime.now()}</p>',
            '</body>',
            '</html>',
            ]
        return footer

    def __generate_page(self, header, style):
        if not header:
            header = self.__make_header(Path(__file__).parent / "files/header.html", style)
        else:
            header = self.__make_header(Path(header), style)
        table = self.__make_table()
        footer = self.__make_footer()
        return "\n".join(header + table + footer)

    def write(self,filepath="index.html"):
        """
        Write the page to the disk
        """
        with open(filepath,"w") as f:
            f.write(self.content)

    def write_style(self, filepath='.'):
        source = Path(__file__).parent / f"files/{ style }.css"
        dest = Path (filepath) / f"{ style }.css"
        shutil.copy(source, dest)
