#---
name: On every commit

on:
  branch: main

#permissions:
#  id-token: write  # This is required for requesting the JWT
#  contents: write  # This is required for creating a release

jobs:
  new-tag:
    name: Tag api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: "${{ secrets.ED_25519 }}"
      - name: Get version from TOML
        run: |
          version=$(awk '/version/ {gsub("\"","") ; print $3}' pyproject.toml)
          echo "TAG_TOML=${version}" >> "$GITHUB_OUTPUT"
          echo "Version: ${version}"
      - name: Get latest git tag
        id: tag-api
        run: |
          git pull --tags
          tag=$(git tag | awk -F- '/api/ {print $2}'| sort -V | tail -1)
          echo "TAG_GIT=${tag}" >> "$GITHUB_OUTPUT"
          echo "Tag: ${tag}"
      - name: Print versions
        run: |
          echo "TOML: ${{ steps.version-api.outputs.TAG_TOML }}"
          echo "GIT: ${{ steps.tag-api.outputs.TAG_GIT }}"
      - name: Create new git tag
        if: >
          steps.version-api.outputs.TAG_TOML
          !=
          steps.tag-api.outputs.TAG_GIT
        env:
          NEW_TAG: ${{ steps.version-api.outputs.TAG_TOML }}
        run: |
          git tag -f ${NEW_TAG}
          git push origin ${NEW_TAG}
